# Probability of responding to a message (0.0 to 1.0)
answer_rate: 0.1
suffixes:
  ado:
    - "meu pau no seu cunhado"
    - "meu pau entra de lado"
  ada:
    - "meu pau na sua cunhada"
    - "meu pau te fez cilada"
  nte:
    - "meu pau limpou seu dente"
    - "meu pau na sua mente"
  ido:
    - "meu pau no seu ouvido"
  ida:
    - "meu pau deu uma sumida"
  ico:
    - "meu pau soltou um grito"
    - "meu pau no seu botico"
  ica:
    - "meu pau ta de larica"
  ivo:
    - "meu pau super massivo"
  iva:
    - "meu pau é uma diva"
  oso:
    - "meu pau está guloso"
  osa:
    - "meu pau na sua mimosa"
    - "meu pau pede uma prosa"
  dor:
    - "meu pau no seu motor"
    - "meu pau é lutador"
  ora:
    - "meu pau comeu amora"
    - "meu pau cutuca fora"
  ão:
    - "meu pau na sua mão"
    - "meu pau no seu botão"
  eza:
    - "meu pau tem certeza"
    - "meu pau tá uma moleza"
  ura:
    - "meu pau pediu a cura"
  ial:
    - "meu pau celestial"
    - "meu pau sensacional"
  sta:
    - "meu pau foi no dentista"
    - "meu pau virou cientista"
  ina:
    - "meu pau com purpurina"
  rio:
    - "meu pau no seu bombrio"
  rva:
    - "meu pau entra faz curva"
  ift:
    - "meu pau entra de drift"
  eta:
    - "meu pau de bicicleta"
  ete:
    - "meu pau de patinete"

