# Probability of responding to a message (0.0 to 1.0)
answer_rate: 1
suffixes:
  ado:
    - "meu pau no seu cunhado"
    - "meu pau entra de lado"
    - "meu pau no seu consagrado"
    - "meu pau no seu mais procurado"
  ada:
    - "meu pau na sua cunhada"
    - "meu pau te fez cilada"
  nte:
    - "meu pau socou seus dente"
    - "meu pau na sua mente"
    - "meu pau te rasgou decente"
    - "meu pau tá persistente"
  ido:
    - "meu pau no seu ouvido"
    - "meu pau a polícia seu cu o perseguido"
  ida:
    - "meu pau deu uma sumida"
    - "meu pau fez uma corrida"
  ico:
    - "meu pau soltou um grito"
    - "meu pau no seu botico"
    - "meu pau entrou bonito"
  ica:
    - "meu pau ta de larica"
    - "meu pau virou notícia"
    - "meu pau causou rebuliça"
  ivo:
    - "meu pau super massivo"
    - "meu pau tá explosivo"
    - "meu pau é agressivo"
  iva:
    - "meu pau é uma diva"
  oso:
    - "meu pau está guloso"
    - "meu pau tá perigoso"
  osa:
    - "meu pau na sua mimosa"
    - "meu pau eu lírico vc canta uma prosa"
    - "meu pau na sua flor rosa"
  dor:
    - "meu pau no seu motor"
    - "meu pau é lutador"
    - "meu pau é destruidor"
    - "meu pau causa terror"
  ora:
    - "meu pau comeu amora"
    - "meu pau cutuca fora"
    - "meu pau chegou agora"
  ão:
    - "meu pau na sua mão"
    - "meu pau no seu botão"
    - "meu pau é teu patrão"
  eza:
    - "meu pau tem certeza"
    - "meu pau é uma beleza"
    - "meu pau é fortaleza"
  ura:
    - "meu pau pediu a cura"
    - "meu pau fez figura"
    - "meu pau tá na loucura"
  ial:
    - "meu pau celestial"
    - "meu pau sensacional"
    - "meu pau é brutal"
  sta:
    - "meu pau foi no dentista"
    - "meu pau virou cientista"
    - "meu pau virou artista"
    - "meu pau fez entrevista"
  ina:
    - "meu pau com purpurina"
    - "meu pau a vassoura teu cu é a faxina"
    - "meu pau é o cloro teu cu é a piscina"
  rio:
    - "meu pau no seu bombrio"
    - "meu pau empurra navio"
  rva:
    - "meu pau entra faz curva"
    - "meu pau girou a tua turva"
    - "meu pau dança na chuva"
  ift:
    - "meu pau entra de drift"
  eta:
    - "meu pau de bicicleta"
    - "meu pau te mete a caneta"
    - "meu pau é um cometa"
  ete:
    - "meu pau de patinete"
    - "meu pau de mobilete"
  eco:
    - "meu pau não faz eco"
  ulo:
    - "meu pau te pega no pulo"
  ejo:
    - "meu pau no teu rio tejo"
  iço:
    - "meu pau roliço"
  ugo:
    - "meu pau no seu vitor hugo"
  ato:
    - "meu pau pequeno grande é do olivato"
  oco:
    - "meu pau no seu oco"
