# Probability of responding to a message (0.0 to 1.0)
answer_rate: 1
suffixes:
  ado:
    - "meu pau no seu cunhado"
  ada:
    - "meu pau na sua cunhada"
  nte:
    - "meu pau limpou seu dente"
  ido:
    - "meu pau no seu ouvido"
  ida:
    - "meu pau deu uma sumida"
  ico:
    - "meu pau soltou um grito"
  ica:
    - "meu pau ta de larica"
  ivo:
    - "meu pau super massivo"
  iva:
    - "meu pau é uma diva"
  oso:
    - "meu pau está guloso"
  osa:
    - "meu pau na sua mimosa"
  dor:
    - "meu pau no seu motor"
  ora:
    - "meu pau comeu amora"
  ão:
    - "meu pau na sua mão"
  eza:
    - "meu pau tem certeza"
  ura:
    - "meu pau pediu a cura"
  ial:
    - "meu pau celestial"
  sta:
    - "meu pau foi no dentista"
  ina:
    - "meu pau com purpurina"
  rio:
    - "meu pau no seu bombrio"





































